name: 'Test actions'
description: 'Test'
inputs:
  access-token:
    description: 'GitHub access token'
    required: false
    default: ${{ github.token }}
  repository_owner:
    description: 'Owner of the target repository (default: owner of the current repository)'
    required: false
  repository_name:
    description: 'Target repository name (default: current repository)'
    required: false
  issue_number:
    description: 'Target repository name (default: current issue number)'
    required: false
  labels:
    description: 'Tracking labels (splitted comma)'
    required: false
  project_columns:
    description: 'Tracking project columns(splitted comma)'
    required: false
  issue_comment:
    description: 'Additional issue comment'
    required: false
outputs:
  labeled_duration_details:
    description: 'Duration of labeling (JSON format)'
runs:
  using: 'node12'
  main: 'dist/index.js'
