name: 'Test actions'
description: 'Test'
inputs:
  access-token:
    description: 'GitHub access token'
    required: true
  labels:
    description: 'Tracking labels (splitted comma)'
    required: false
  project_columns:
    description: 'Tracking project columns(splitted comma)'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
