name: issue-closed

on:
  issues:
    types:
      - closed
      - labeled

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Report
        uses: ./
