name: issue-closed

on:
  issues:
    types:
      - closed

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Report
        id: report
        uses: ./
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          labels: label1,label2,ラベルA
          project_columns: TODO,Doing
      - name: echo
        shell: bash
        run: echo "${{ steps.report.outputs.labeled_duration_details }}"
