name: issue-closed

on:
  issues:
    types:
      - closed

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Report
        uses: ./
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
